[package]
name = "Financial-Manager"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = ">= 0.4.39, < 1.0.0"
regex = ">= 1.11.1, < 2.0.0"
eframe = ">= 0.31.0, < 1.0.0"
egui_extras = ">= 0.31.0, < 1.0.0"
rusqlite = { version = ">= 0.33.0, < 1.0.0", features = ["bundled"] }
